import React from 'react';
import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import Nav from './Nav';

const Layout = ({ children }: { children: React.ReactNode | undefined }) => (
  <React.Fragment>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav />
    <div className={styles.container}>
      <main className={styles.main}>{children}</main>
    </div>
  </React.Fragment>
);

export default Layout;
